### ISSUE TITLE
Create ai-plugin.json and OpenAPI definition for wellknown.ai

### ISSUE THREAD

**Issue by MikeRalphson** [cfortuner/wellknown#2]
I notice that `wellknown.ai` has an API, but it doesn't yet have its own `ai-plugin.json` or `openapi.yaml|json`. Adding these would possibly allow querying of the list of wellknown plugins using `wellknown.ai` itself. Meta. Inception.

**Comment by cfortuner** [comment]
Yes! good idea

**Comment by cfortuner** [comment]
added a initial version! will update it more soon!
