### ISSUE TITLE
Add back in swagger-ui and/or ReDoc in new details tabs

### ISSUE THREAD

**Issue by MikeRalphson** [cfortuner/wellknown#8]
Hosted versions can be called with:

* https://petstore.swagger.io/?url={{openapi-url}}
* https://redocly.github.io/redoc?url={{openapi-url}}

**Comment by cfortuner** [comment]
Added back the proxy and the swagger ui component.

Let me know if this works for you!

**Comment by MikeRalphson** [comment]
Hmm, can't see them. Where do I go?

**Comment by cfortuner** [comment]
Oops sorry the build failed. Just fixed it!

https://www.wellknown.ai/plugin/APIs-guru

**Comment by MikeRalphson** [comment]
Getting a 504 now...

**Comment by MikeRalphson** [comment]
Resolved, thanks.
